spring:
  application:
    name: eBanking
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: p123
      # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/auth/realms/ebank
          jwk-set-uri: http://localhost:8088/auth/realms/ebank/protocol/openid-connect/certs
server:
  port: 8088
  servlet:
    context-path: /ebanking
